### ISSUE TITLE
Missing project description

### ISSUE THREAD

**Issue by chocolateboy** [boosterfuels/monogram#4]
This is an interesting project, and the idea behind it is inspiring. It has made me start looking for other areas where this approach can be applied. 🕺 🎉 

But I forgot what it was called, couldn't remember any other details about the (fantastic) [write-up](http://thecodebarbarian.com/introducing-monogram-the-anti-odm-for-mongodb-nodejs.html), couldn't find it in /r/javascript, and couldn't find it among my GitHub stars. I eventually found it on /r/node after a long search, but would have found it straight away if this, or something similar, was set as the project's GitHub description:

> Action-based anti-ODM for MongoDB and Node.js

(You could also add some [topics](https://github.com/blog/2309-introducing-topics) while you're at it — apart from "MongoDB", I also searched for "stream", "Mongoose", and "serialize(d)", amongst other things.)

**Comment by vkarpov15** [comment]
Thanks! If you're interested in this, I've started tinkering with generalizing the concept of converting function calls to objects in [this lib](https://github.com/vkarpov15/tao). I'll add the topics you suggested, thanks :+1:

**Comment by chocolateboy** [comment]
Thanks!

FYI, the blog post link is wrong i.e.:

```
Read the [intro blog post here](git@github.com:boosterfuels/monogram.git).
```

should (presumably) be:

```
Read the [intro blog post here](http://thecodebarbarian.com/introducing-monogram-the-anti-odm-for-mongodb-nodejs.html).
```

Also, while the NPM keywords are nice, I was thinking specifically of [GitHub topics](https://github.com/blog/2309-introducing-topics). (Starred repos don't come up as [search results](https://github.com/blog/1236-searching-and-filtering-stars) unless the search terms appear in the repo's name, [GitHub description](https://stackoverflow.com/a/21649064), or GitHub topics.)

**Comment by vkarpov15** [comment]
Nice catch, my mistake :+1: I added some GitHub topics too, thanks for the link, I didn't know about that.
